# "org" ensures this Service is used with the correct Serverless Framework Access Key.

package:
  patterns:
    - '!amplify'
    - '!distrokid'
    - '!example data objects'
    - '!google'
    - '!scripts/songkick-scraper'
    - '!polly'
    - '!sql'
    - '!src'
    - '!utility/static-utility-records/top_us_singles_playlists/**'
org: soundfoundio
service: showcase-backend-app
provider:
  profile: default
  name: aws
  runtime: nodejs20.x
  stage: dev
  region: us-east-1
  memorySize: 3500
functions:
#  express -> serverless -> gateway api easiest route possible = just one function, handles everything
  app:
    handler: app.handler
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true
