module.exports.list = ['David Bowie - The Rise and Fall of Ziggy Stardust and the Spiders from Mars ALBUM REVIEW',
 'The Microphones - The Glow Pt. 2 ALBUM REVIEW',
 'Yes - Close to the Edge ALBUM REVIEW',
 'Nirvana - In Utero ALBUM REVIEW',
 'Nas - Illmatic ALBUM REVIEW',
 'Patti Smith - Horses ALBUM REVIEW',
 'Radiohead - Kid A ALBUM REVIEW',
 'DJ Shadow - Endtroducing..... ALBUM REVIEW',
 'N.W.A. - Straight Outta Compton ALBUM REVIEW',
 'Slint - Spiderland ALBUM REVIEW',
 'Bob Dylan - Highway 61 Revisited ALBUM REVIEW',
 'Tangerine Dream - Phaedra ALBUM REVIEW',
 'Roland Kirk - I Talk With the Spirits ALBUM REVIEW',
 'Kate Bush - Hounds of Love ALBUM REVIEW',
 'Iron Maiden - The Number of the Beast ALBUM REVIEW',
 'Kraftwerk - Trans-Europe Express ALBUM REVIEW',
 'A Tribe Called Quest- The Low End Theory ALBUM REVIEW',
 'Joy Division - Unknown Pleasures ALBUM REVIEW',
 'Nina Simone - Pastel Blues ALBUM REVIEW',
 'Prince and the Revolution - Purple Rain ALBUM REVIEW',
 'Fugazi - Repeater ALBUM REVIEW',
 'Johnny Cash - At Folsom Prison ALBUM REVIEW',
 'The Velvet Underground & Nico - Self-Titled ALBUM REVIEW',
 'Miles Davis- Bitches Brew ALBUM REVIEW',
 'My Bloody Valentine- Loveless ALBUM REVIEW',
 'King Crimson- In the Court of the Crimson King ALBUM REVIEW',
 'Dead Kennedys- Plastic Surgery Disasters ALBUM REVIEW',
 'Madvillain- Madvillainy ALBUM REVIEW',
 'Neutral Milk Hotel - In the Aeroplane Over the Sea ALBUM REVIEW',
 "Marvin Gaye- What's Going On", 'Wu-Tang Clan- Enter the Wu-Tang: 36 Chambers ALBUM REVIEW',
 'Frank Zappa- Hot Rats ALBUM REVIEW',
 'Godspeed You! Black Emperor- Lift Yr. Skinny Fists Like Antennas to Heaven! ALBUM REVIEW',
 'Mac Miller: NPR Music Tiny Desk Concert',
 "THE WORST ALBUM OF 2016 (Corey Feldman's Angelic 2 The Core) [NOT GOOD]", 'Dunkey Streams Elden Ring (Day 1)',
 'Louis CK on Huck Finn',
 'Mix - Cocteau Twins - Heaven or Las Vegas ALBUM REVIEW',
 'The Dreampop Enigma of Cocteau Twins & LORELEI | New British Canon',
 "Jimmy Hides A Battery In Chuck's Pocket | Chicanery | Better Call Saul", 'Eric Andre Ranks Eric Andre Show Pranks',
 "'Hot Ones' Guests Impressed by Sean Evans' Questions (Seasons 13-15)", 'Can You Beat Elden Ring WITHOUT Attacking? (Pacifist Run)',
 'Radiohead: Worst To Best',
 'Jon Batiste: NPR Music Tiny Desk Concert',
 'Microsoft Sucks',
 `How "It's Always Sunny in Philadelphia" Changed Comedy Forever`, 'Why Is Conservative Comedy So… Not Very Good? - SOME MORE NEWS',
 'Horizon Forbidden West All Valor Surges & Which To Use! (Horizon Forbidden West Valor Surge)',
 '2022 GRAMMY Awards Recap and Reaction!',
 'Nirvana - In Utero ALBUM REVIEW',
 'Robert Pattinson Breaks Down His Most Iconic Characters | GQ',
 'Gordon Ramsay Savagely Critiques Spicy Wings | Hot Ones']
