module.exports.list = [
  "Kilo Kish - American Gurl ALBUM REVIEW",
  "Denzel Curry - Melt My Eyez See Your Future ALBUM REVIEW",
  "Soul Glo - Diaspora Problems ALBUM REVIEW",
  "Bladee & Ecco2k - Crest ALBUM REVIEW",
  "Benny the Butcher - Tana Talk 4 ALBUM REVIEW",
  "Charlotte Adigéry & Bolis Pupul - Topical Dancer ALBUM REVIEW",
  "Conway the Machine - God Don't Make Mistakes ALBUM REVIEW",
  "Black Dresses - Forget Your Own Face ALBUM REVIEW",
  "Beach House - Once Twice Melody ALBUM REVIEW",
  "Big Thief - Dragon New Warm Mountain I Believe in You ALBUM REVIEW",
  "Black Country, New Road - Ants from Up There ALBUM REVIEW",
  "Silvana Estrada - Marchita ALBUM REVIEW",
  "Krallice - Crystalline Exhaustion ALBUM REVIEW",
  "foxtails - fawn ALBUM REVIEW",
  "FKA twigs - Caprisongs MIXTAPE REVIEW",
  "The Weeknd - Dawn FM ALBUM REVIEW",
  "death's dynamic shroud.wmv - Faith in Persona ALBUM REVIEW",
  "L'Rain - Fatigue ALBUM REVIEW",
  "Arca - KiCk ii-iiiii ALBUM(S) REVIEW",
  "Deerhoof - Actually, You Can ALBUM REVIEW",
  "Richard Dawson & Circle - Henki ALBUM REVIEW",
  "Sloppy Jane - Madison ALBUM REVIEW",
  "JPEGMAFIA - LP! ALBUM REVIEW",
  "EP ❤️: Spy, PinkPantheress, Benny the Butcher, Knocked Loose",
  "James Blake - Friends That Break Your Heart ALBUM REVIEW",
  "Magdalena Bay - Mercurial World ALBUM REVIEW",
  "Blu - The Color Blu(e) ALBUM REVIEW",
  "illuminati hotties - Let Me Do One More ALBUM REVIEW",
  "Wiki - Half God ALBUM REVIEW",
  "Westside Gunn - Hitler Wears Hermes 8 ALBUM REVIEW",
  "Sufjan Stevens & Angelo De Augustine - A Beginner's Mind ALBUM REVIEW",
  "Injury Reserve - By the Time I Get to Phoenix ALBUM REVIEW",
  "Low - HEY WHAT ALBUM REVIEW",
  "Little Simz - Sometimes I Might Be Introvert ALBUM REVIEW",
  "Turnstile - Glow On ALBUM REVIEW",
  "Pink Siifu - GUMBO'! ALBUM REVIEW",
  "Yola - Stand for Myself ALBUM REVIEW",
  "Lingua Ignota - Sinner Get Ready ALBUM REVIEW",
  "Nas - King's Disease II ALBUM REVIEW",
  "EP ❤️: Poppy, Blu & Sirplus, Yves Tumor",
  "Twin Shadow - Twin Shadow ALBUM REVIEW",
  "Spellling - The Turning Wheel ALBUM REVIEW",
  "Tyler, the Creator - Call Me If You Get Lost ALBUM REVIEW",
  "Backxwash - I Lie Here Buried with My Rings and My Dresses ALBUM REVIEW",
  "black midi - Cavalcade ALBUM REVIEW",
  "Panopticon - ...And Again Into the Light ALBUM REVIEW",
  "St. Vincent - Daddy's Home ALBUM REVIEW",
  "Sematary - Rainbow Bridge 3 MIXTAPE REVIEW",
  "Porter Robinson - Nurture ALBUM REVIEW",
  "Jeff Rosenstock - SKA DREAM ALBUM REVIEW",
  "EP ❤️: YUKIKA, Vic Mensa, Courting, Gallant",
  "BROCKHAMPTON - ROADRUNNER: NEW LIGHT, NEW MACHINE ALBUM REVIEW",
  "Floating Points, Pharoah Sanders & The LSO - Promises ALBUM REVIEW",
  "Armand Hammer & The Alchemist - Haram ALBUM REVIEW",
  "Feu! Chatterton - Palais d'Argile ALBUM REVIEW",
  "EP ❤️: Matt Ox, Show Me the Body, Chika, Space Laces",
  "Genesis Owusu - Smiling with No Teeth ALBUM REVIEW",
  "Nick Cave & Warren Ellis - Carnage ALBUM REVIEW",
  "Ad Nauseam - Imperative Imperceptible Impulse ALBUM REVIEW",
  "Black Dresses - Forever in Your Heart ALBUM REVIEW",
  "slowthai - TYRON ALBUM REVIEW",
  "EP ❤️: Luna Li, Jute Gyte, Lingua Ignota, JPEGMAFIA",
  "Black Country, New Road - For the first time ALBUM REVIEW",
  "Weezer - OK Human ALBUM REVIEW",
  "EP ❤️: Arca, Beach Bunny, and Cosmo Pyke",
  "Moor Mother & billy woods - BRASS ALBUM REVIEW",
  "Jazmine Sullivan - Heaux Tales EP REVIEW",
  "Viagra Boys - Welfare Jazz ALBUM REVIEW",
  "Gorillaz - Plastic Beach REDUX REVIEW",
  "Ichiko Aoba - Windswept Adan ALBUM REVIEW",
  "Boldy James & Sterling Toles - Manger on McNichols ALBUM REVIEW",
  "The Koreatown Oddity - Little Dominiques Nosebleed ALBUM REVIEW",
  "Liturgy - Origin of the Alimonies ALBUM REVIEW",
  "Undeath - Lesions of a Different Kind ALBUM REVIEW",
  "Chris Stapleton - Starting Over ALBUM REVIEW",
  "Bring Me the Horizon - POST HUMAN: SURVIVAL HORROR EP REVIEW",
  "Adrianne Lenker - Songs ALBUM REVIEW",
  "clipping. - Visions of Bodies Being Burned ALBUM REVIEW",
  "Gorillaz - Song Machine, Season One: Strange Timez ALBUM REVIEW",
  "Dorian Electra - My Agenda ALBUM REVIEW",
  "Idles - Ultra Mono ALBUM REVIEW",
  "Slauson Malone - Vergangenheitsbewältigung EP REVIEW | IT'S GOOD!",
  "Sevdaliza - Shabrang ALBUM REVIEW",
  "The Flaming Lips - American Head ALBUM REVIEW",
  "Conway the Machine - From King to a GOD ALBUM REVIEW",
  "Meridian Brothers - Cumbia Siglo XXI ALBUM REVIEW",
  "Matmos - The Consuming Flame: Open Exercises in Group Form ALBUM REVIEW",
  "Tkay Maidza - Last Year Was Weird Vol. 2 EP REVIEW",
  "Imperial Triumphant - Alphaville ALBUM REVIEW",
  "Blu & Exile - Miles ALBUM REVIEW",
  "Lianne La Havas - Self-Titled ALBUM REVIEW",
  "Boris - No ALBUM REVIEW",
  "Jessie Ware - What's Your Pleasure? ALBUM REVIEW",
  "HAIM - Women in Music Pt. III ALBUM REVIEW",
  "Phoebe Bridgers - Punisher ALBUM REVIEW",
  "Moor Jewelry - True Opera ALBUM REVIEW",
  "Chloe x Halle - Ungodly Hour ALBUM REVIEW",
  "Run the Jewels - RTJ4 ALBUM REVIEW",
  "Deerhoof - Future Teenage Cave Artists ALBUM REVIEW",
  "Freddie Gibbs & The Alchemist - Alfredo ALBUM REVIEW w/DeadEndHipHop",
  "Backxwash - God Has Nothing to Do With This Leave Him Out of It ALBUM REVIEW",
  "Jeff Rosenstock - NO DREAM ALBUM REVIEW",
  "Perfume Genius - Set My Heart on Fire Immediately ALBUM REVIEW",
  "Charli XCX - how i'm feeling now ALBUM REVIEW",
  "Natalia Lafourcade - Un Canto por México Vol. 1 ALBUM REVIEW",
  "Dope Body - Home Body ALBUM REVIEW",
  "Black Dresses - Peaceful as Hell ALBUM REVIEW",
  "Quelle Chris & Chris Keys - Innocent Country 2 ALBUM REVIEW",
  "Lido Pimienta - Miss Colombia ALBUM REVIEW",
  "Rina Sawayama - Sawayama ALBUM REVIEW",
  "Laura Marling - Song for Our Daughter ALBUM REVIEW",
  "The Strokes - The New Abnormal ALBUM REVIEW",
  "Dirty Projectors - Windows Open EP REVIEW | It's Good!",
  "Nicolas Jaar - Cenizas ALBUM REVIEW",
  "Horse Lords - The Common Task ALBUM REVIEW",
  "Haru Nemuri - Lovetheism MINI-ALBUM REVIEW | It's Good!",
  "R.A.P. Ferreira - Purple Moonlight Pages ALBUM REVIEW",
  "Code Orange - Underneath ALBUM REVIEW",
  "Disclosure - Ecstasy EP REVIEW | It's Good!",
  "King Krule - Man Alive! ALBUM REVIEW",
  "HMLTD - West of Eden ALBUM REVIEW",
  "Against All Logic - 2017–2019 ALBUM REVIEW",
  "Denzel Curry x Kenny Beats - Unlocked ALBUM REVIEW",
  "Dan Deacon - Mystic Familiar ALBUM REVIEW",
  "Poppy - I Disagree ALBUM REVIEW",
  "Stormzy - Heavy Is the Head ALBUM REVIEW",
  "Mac Miller - Circles ALBUM REVIEW",
  "Yazz Ahmed - Polyhymnia ALBUM REVIEW",
  "Liturgy - H.A.Q.Q. ALBUM REVIEW",
  "Matana Roberts - COIN COIN Chapter Four: Memphis ALBUM REVIEW",
  "Anamanaguchi - [USA] ALBUM REVIEW",
  "Sunn O))) - Pyroclasts ALBUM REVIEW",
  "clipping. - There Existed an Addiction to Blood ALBUM REVIEW",
  "Caroline Polachek - Pang ALBUM REVIEW",
  "Guerilla Toss - What Would the Odd Do? EP REVIEW | It's Good!",
  "Lightning Bolt - Sonic Citadel ALBUM REVIEW",
  "Ana Frango Elétrico - Little Electric Chicken Heart ALBUM REVIEW",
  "Richard Dawson - 2020 ALBUM REVIEW",
  "Kero Kero Bonito - Civilisation I EP REVIEW | It's Good!",
  "Danny Brown - uknowhatimsayin¿ ALBUM REVIEW",
  "Hobo Johnson - The Fall of Hobo Johnson ALBUM REVIEW",
  "The Highwomen - Self-Titled ALBUM REVIEW",
  "Charli XCX - Charli ALBUM REVIEW",
  "JPEGMAFIA - All My Heroes Are Cornballs ALBUM REVIEW",
  "Alex Cameron - Miami Memory ALBUM REVIEW",
  "Tropical [Frick] Storm - Braindrops ALBUM REVIEW",
  "Lana Del Rey - Norman [Fricking] Rockwell! ALBUM REVIEW",
  "BROCKHAMPTON - GINGER ALBUM REVIEW",
  "King Gizzard & The Lizard Wizard - Infest the Rats' Nest ALBUM REVIEW",
  "Purple Mountains - Self-Titled ALBUM REVIEW",
  "Dorian Electra - Flamboyant ALBUM REVIEW",
  "Lingua Ignota - Caligula ALBUM REVIEW",
  "Uboa - The Origin of My Depression ALBUM REVIEW",
  "Freddie Gibbs & Madlib - Bandana ALBUM REVIEW",
  "Kirin J. Callinan - Return to Center ALBUM REVIEW",
  "Prince - Originals ALBUM REVIEW",
  "black midi - Schlagenheim ALBUM REVIEW",
  "Daphni - Sizzling EP REVIEW",
  "Otoboke Beaver - Itekoma Hits ALBUM REVIEW",
  "Denzel Curry - ZUU ALBUM REVIEW",
  "slowthai - Nothing Great About Britain ALBUM REVIEW",
  "Tyler, the Creator - IGOR ALBUM REVIEW",
  "Slauson Malone - A Quiet Farwell, 2016–2018 ALBUM REVIEW",
  "Beyoncé - Homecoming ALBUM REVIEW",
  "Lizzo - Cuz I Love You ALBUM REVIEW",
  "PUP - Morbid Stuff ALBUM REVIEW",
  "Weyes Blood - Titanic Rising ALBUM REVIEW",
  "Quelle Chris - Guns ALBUM REVIEW",
  "Billy Woods & Kenny Segal - Hiding Places ALBUM REVIEW",
  "The Comet Is Coming - Trust in the Lifeforce of the Deep Mystery ALBUM REVIEW",
  "Billie Eilish - When We All Fall Asleep, Where Do We Go? ALBUM REVIEW",
  "Flume - Hi This Is Flume MIXTAPE REVIEW",
  "Matmos - Plastic Anniversary ALBUM REVIEW",
  "Little Simz - Grey Area ALBUM REVIEW",
  "Blu & Oh No - A Long Red Hot Los Angeles Summer Night ALBUM REVIEW",
  "Kankyō Ongaku: Japanese Ambient, Environmental & New Age Music 1980​-​90 COMPILATION REVIEW",
  "Xiu Xiu - Girl with Basket of Fruit ALBUM REVIEW",
  "Ariana Grande - thank u, next ALBUM REVIEW",
  "Malibu Ken - Self-Titled ALBUM REVIEW",
  "Marquis Hill - Modern Flows, Vol. 2 ALBUM REVIEW",
  "Earl Sweatshirt - Some Rap Songs ALBUM REVIEW",
  "J.I.D - DiCaprio 2 ALBUM REVIEW",
  "Anderson .Paak - Oxnard ALBUM REVIEW",
  "Rosalía - El mal querer ALBUM REVIEW",
  "Julia Holter - Aviary ALBUM REVIEW",
  "Daughters - You Won't Get What You Want ALBUM REVIEW",
  "Current 93 - The Light Is Leaving Us All ALBUM REVIEW",
  "Polyphia - New Levels New Devils ALBUM REVIEW",
  "Horrendous - Idol ALBUM REVIEW",
  "twenty one pilots - Trench ALBUM REVIEW",
  "Kero Kero Bonito - Time 'n' Place ALBUM REVIEW",
  "Guerilla Toss - Twisted Crystal ALBUM REVIEW",
  "Noname - Room 25 ALBUM REVIEW",
  "Aphex Twin - Collapse EP REVIEW",
  "Armand Hammer - Paraffin ALBUM REVIEW",
  "IDLES - Joy as an Act of Resistance. ALBUM REVIEW",
  "Blood Orange - Negro Swan ALBUM REVIEW",
  "Hermit and the Recluse - Orpheus vs. the Sirens ALBUM REVIEW",
  "Louis Cole - Time ALBUM REVIEW",
  "Iglooghost - Clear Tamei / Steel Mogu EP REVIEW",
  "Weekend Update: Biden’s Approval Rating Drops, Elon Musk Wants to Buy Twitter - SNL",
  "Mystery Meat: A Search for the Truth",
  "My Most HATED Reviews",
  "Neopets",
  "Major Biden Embroiled In White House Scandal | The Weather Channel Is Our Most Trusted Source",
  "21 Minutes of Nate Bargatze | Netflix Is A Joke",
  "THE WORST ALBUM OF 2016 (Corey Feldman's Angelic 2 The Core) [NOT GOOD]",
  "24/7 TRAPPIN IN JAPAN  //  phonk / lofi hip hop  / vapor trap Radio °   🎧 💨 🚌",
  "Worms",
  "Kishi Bashi: NPR Music Tiny Desk Concert",
  "Why Love & Mercy is the best music biopic",
  "Radiohead - In Rainbows From the Basement (April 2008)",
  "Brian Tyree Henry Breaks Down Atlanta's Biggest Moments | GQ",
  "10 Times I Changed My Opinion On Albums Pt. 2",
  "Can You Beat Elden Ring WITHOUT Attacking? (Pacifist Run)",
  "Eric Andre Ranks Eric Andre Show Pranks",
  "Elden Ring's Lore: Explained!",
  "Fortnite Daycare",
  "Machine Gun Kelly - Mainstream Sellout ALBUM REVIEW",
];
